### ISSUE TITLE
Microsoft Azure backed Delta tables 

### ISSUE THREAD

**Issue by rbacevic** [delta-incubator/delta-sharing-rs#18]
### Contact Details

ranko.bacevic@dev.telnet.rs

### Is your feature request related to a problem? Please describe.

I was trying to connect sharing server with ADLS gen 2, but I am getting internal server error once I execute request.

### Describe the solution you'd like.

Hi,
is supporting Microsoft Azure backed Delta tables in development? Is there some estimate when it is expected to be done, or if help is needed, I can try to help, with some minor guidelines and info from someone in charge :) ?
Thanks in advance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tdikland** [comment]
I'd like to work on supporting ADLS backed Delta Lake tables. @MrPowers can you assign this issue to me?

**Comment by tdikland** [comment]
@ognis1205 I've opened a draft PR to support ADLS backed Delta Tables. There are some open questions, so it would be great if you could take a look.
